#! /usr/bin/env groovy

def imageName = 'starlord.inscloudgate.net/deploy/bridge-cdp-cypress'

pipeline {
  agent { label 'docker' }

  stages {
    stage('Build image') {
      steps {
        sh """
          docker build \
            -t "$imageName:latest" \
            -t "$imageName:$GIT_COMMIT" \
            -f ci/smoketests/Dockerfile \
            .
        """
        sh "docker push $imageName:$GIT_COMMIT"
        sh "docker push $imageName:latest"
      }
    }
  }
}
